### 함수 

In [4]:
# 문제1: 구구단 출력 함수 만들기 (입력값에 대한 구구단 함수 출력)
fun1 <- function(x){
    for (i in 1:9){
        cat(x,"x",i,"=",x*i,"\n")
    }
}
fun1(3)
cat("\n")
fun1(6)

3 x 1 = 3 
3 x 2 = 6 
3 x 3 = 9 
3 x 4 = 12 
3 x 5 = 15 
3 x 6 = 18 
3 x 7 = 21 
3 x 8 = 24 
3 x 9 = 27 

6 x 1 = 6 
6 x 2 = 12 
6 x 3 = 18 
6 x 4 = 24 
6 x 5 = 30 
6 x 6 = 36 
6 x 7 = 42 
6 x 8 = 48 
6 x 9 = 54 


### R 데이터 타입

In [14]:
x <- 8
class(x)

[1] "numeric"

In [15]:
y <- "kim"
class(y)

[1] "character"

In [16]:
z <- factor(c("T","F","TF"))
class(z)

[1] "factor"

In [17]:
w <- as.logical(c(1,0,1,0))
w

[1]  TRUE FALSE  TRUE FALSE

### R 데이터 구조 

#### 1. 벡터 

In [1]:
x <- c(1,2,3,4,5)
x

[1] 1 2 3 4 5

In [2]:
x[2]

[1] 2

In [3]:
x[4] <- 0 
x

[1] 1 2 3 0 5

In [5]:
c(x,4)

[1] 1 2 3 0 5 4

#### 2. 행렬(Matrix)
##### 행렬은 동일한 형으로 구성된 2차원의 데이터 구조이며, 배열의 한 형태 
##### 배열은 다차원이나 행렬은 '행','열'의 속성을 갖는 2차원
##### 행렬은 만드는 방법은 matrix()함수를 이용하며, '열 우선 배열' 방식으로 생성됨 

In [21]:
x <- matrix(c(1,2,3,4),nrow = 2, ncol = 2)
x

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [24]:
#row와 columns을 설정해주지 않아 한줄로 행렬이 생성 
x <- matrix(c(1,2,3,4))
x


[,1]
[1,] 1   
[2,] 2   
[3,] 3   
[4,] 4

In [26]:
# row와 columns을 설정해주고  byrow를 활용하여 행 우선배열로 변경
y <- matrix(c(1,2,3,4),nrow = 2,ncol = 2, byrow = T)
y

[,1] [,2]
[1,] 1    2   
[2,] 3    4

In [27]:
# 행렬 - 벡터를 활용한 행렬 생성 
r1 <- c(1,4,7)
r2 <- c(2,5,8)
r3 <- c(3,6,9)
# rbind = row을 기준으로 병합
rbind(r1,r2,r3)

[,1] [,2] [,3]
r1 1    4    7   
r2 2    5    8   
r3 3    6    9

In [28]:
c1 <- 1:3
c2 <- 4:6
c3 <- 7:9
# cbind = columns을 기준으로 병합
cbind(c1,c2,c3)

c1 c2 c3
[1,] 1  4  7 
[2,] 2  5  8 
[3,] 3  6  9

#### 3. 배열 
##### 배열은 행렬을 2차원 이상으로 확장시킨 데이터 구조
##### 행렬은 2차원이지만 배열은 필요에 따라 3차원, 4차원 .. 임의의 차원을 생성 할 수 있음
##### 배열의 생성은 array()와 dim() 함수를 이용하여 각 차원의 요소 수를 벡터로 지정 

In [29]:
array(1:6)

[1] 1 2 3 4 5 6

In [30]:
array(1:6,c(2,3))


[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [32]:
array(1:8, c(2,2,2)) ### 1 ~ 8의 자료로 3차원 배열 생성, 주피터 노트북에선 활용이 안되는듯

, , 1

     [,1] [,2]
[1,]    1    3
[2,]    2    4

, , 2

     [,1] [,2]
[1,]    5    7
[2,]    6    8

, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

, , 2

     [,1] [,2] [,3] [,4]
[1,]   13   16   19   22
[2,]   14   17   20   23
[3,]   15   18   21   24

#### 4. 데이터 프레임 
##### 데이터 프레임은 행렬과 비슷한 형태로 되어 있으나, 행렬은 차원으로 표시되며 같은 데이터 형태를 갖는 반면에, 데이터 프레임은 각 열들이 서로 다른 형태의 데이터 유형을 포함할 수 있음 
##### 범주형 변수를 가질 수도 있기 때문에 범주형 자료 분석에도 유용하게 사용
##### 데이터 프레임의 생성방법은 data.frame()함수 이용 

In [35]:
char1 <- c("A","A","B","B","C")
char1
num1 <- c(1,1,2,2,3)
num1 
test1 <- data.frame(char1,num1)
test1
class(test1)

[1] "A" "A" "B" "B" "C"

[1] 1 1 2 2 3

char1 num1
1 A     1   
2 A     1   
3 B     2   
4 B     2   
5 C     3

[1] "data.frame"

In [38]:
test3 <- rbind(test1,c("C",4))
test3

char1 num1
1 A     1   
2 A     1   
3 B     2   
4 B     2   
5 C     3   
6 C     4

In [37]:
test2 <- cbind(test1,married = c(T,T,T,F,F))
test2

char1 num1 married
1 A     1     TRUE  
2 A     1     TRUE  
3 B     2     TRUE  
4 B     2    FALSE  
5 C     3    FALSE

#### 5. 리스트 
##### 서로 다른 데이터 형의 집합을 정의할 필요가 있을때 사용할 수 있는 데이터 구조 
##### 리스트는 서로 다른 형태의 데이터로 구성됨
##### 리스트 생성 함수는 list()

In [19]:
test <- list("kim",c(94,82,92),c(T,F,T)) # list(문자, 숫자, 논리형 데이터 )
test
test[[1]]
test[[2]]
test[[3]]
test[[3]][3]

[[1]]
[1] "kim"

[[2]]
[1] 94 82 92

[[3]]
[1]  TRUE FALSE  TRUE

[1] "kim"

[1] 94 82 92

[1]  TRUE FALSE  TRUE

[1] TRUE

In [7]:
# 리스트 성분별 이름 정의하기 
son <- list(son.name = c("Minsu","Minchul"), son.gender = c("Male","Male"),son.age = c(2,6))
son

$son.name
[1] "Minsu"   "Minchul"

$son.gender
[1] "Male" "Male"

$son.age
[1] 2 6

In [11]:
son[[2]]
son[[3]][2]
names(son) <- c("name","gender","age")
son$name
son$gender
son$age

[1] "Male" "Male"

[1] 6

[1] "Minsu"   "Minchul"

[1] "Male" "Male"

[1] 2 6

### R 데이터 파일 관리 

#### 프로그램 설정 경로 확인 

In [3]:
# 현재 작업중인 파일 경로 확인
getwd()

[1] "D:/py_fi/Bigdata_talent"

In [2]:
# 특정 위치를 작업 파일 경로로 설정 
setwd("D:/py_fi/Bigdata_talent")

##### 데이터 파일 R로 불러오기 

In [18]:
# txt파일 
student_list = read.table(file ='studentlist.txt',sep = ",",header = T,stringsAsFactors = FALSE)
# file: 불러올 파일의 경로와 파일명, 현재의 작업 경로에서 불러올 경우 파일명만 작성 
# header = 'T'이면 데이터의 첫 번째 행을 열 이름으로,'F'이면 첫 번째 행부터 데이터로 사용
# sep = 구분자, 기본탭(\t)
# StringAsFactors: "T"이면 문자형 변수를 범주형으로 변환, 'F'면 문자형 변수 그대로 사용

In [19]:
student_list

name   sex  age grade absence bloodtype height weight
1  김길동 남자 23  3     유      O         165.3  68.2  
2  이미린 여자 22  2     무      AB        170.1  53.0  
3  홍길동 남자 24  4     무      B         175.0  80.1  
4  김철수 남자 23  3     무      AB        182.1  85.7  
5  손세수 여자 20  1     유      A         168.0  49.5  
6  박미희 여자 21  2     무      O         162.0  52.0  
7  강수친 여자 22  1     무      O         155.2  45.3  
8  이희수 여자 23  1     무      A         176.9  55.0  
9  이철린 남자 23  3     무      B         178.5  64.2  
10 방희철 남자 22  2     무      B         176.1  61.3  
11 박수호 남자 24  4     유      O         167.1  62.0  
12 임동민 남자 22  2     무      AB        180.0  75.8  
13 김민수 남자 21  1     무      A         162.2  55.3  
14 이희진 여자 23  3     무      O         176.1  53.1  
15 김미진 여자 22  2     무      B         158.2  45.2  
16 김동수 남자 24  4     유      B         168.6  70.2  
17 여수근 남자 21  1     무      A         169.2  62.2

In [25]:
read.csv('example_studentlist.csv',header = T,sep = ',',stringsAsFactors = F)

name   sex  age grade absence bloodtype height weight
1  김길동 남자 23  3     유      O         165.3  68.2  
2  이미린 여자 22  2     무      AB        170.1  53.0  
3  홍길동 남자 24  4     무      B         175.0  80.1  
4  김철수 남자 23  3     무      AB        182.1  85.7  
5  손세수 여자 20  1     유      A         168.0  49.5  
6  박미희 여자 21  2     무      O         162.0  52.0  
7  강수친 여자 22  1     무      O         155.2  45.3  
8  이희수 여자 23  1     무      A         176.9  55.0  
9  이철린 남자 23  3     무      B         178.5  64.2  
10 방희철 남자 22  2     무      B         176.1  61.3  
11 박수호 남자 24  4     유      O         167.1  62.0  
12 임동민 남자 22  2     무      AB        180.0  75.8  
13 김민수 남자 21  1     무      A         162.2  55.3  
14 이희진 여자 23  3     무      O         176.1  53.1  
15 김미진 여자 22  2     무      B         158.2  45.2  
16 김동수 남자 24  4     유      B         168.6  70.2  
17 여수근 남자 21  1     무      A         169.2  62.2

In [ ]:
##### R 데이터 내보내기 

In [28]:
# txt파일 
write.table(student_list,file='bye_student.txt',sep = ',',row.names = F, col.names = T)
# x: 저장할 데이터 
# file : 저장할 경로와 파일명, 현재의 작업 경로에 그대로 저장할 경우 파일명만 작성 
# row.names: 'T'이면 행 이름(번호) 포함, 'F'이면 행 이름(번호)가 생략됨
# col.names: 'T'이면 열 이름 포함, 'F'이면 열 이름 생략하여 저장 

In [30]:
# csv파일 
write.csv(student_list,file='bye_stduent2.csv',row.names = F)
# x: 저장할 데이터
# file: 저장할 경로와 파일명, 현재의 작업 경로에 그대로 저장할 경우 파일명만 작성
# row.names: 'T'이면 행 이름(번호) 포함 'F'면 생략됨