# 1. matrix
# 2. data frame
# 3. matrix, data frame 다루기
# 4. 파일에서 데이터 읽기/쓰기
# 5 list, factor

# 1. matrix
## 분석을 위한 데ㅣ터는 2차원 테이블 형태가 데부분
## vector: 1차원 데이터를 저장하기 위한 자료구조 
## matrix와 data frame의 차이는 matrix는 데이터 타입이 동일하나 data frame은 컬럼별로 다른 데이터 타입을 가질 수 있다. 

In [3]:
# matrix의 생성
z <- matrix(1:20,nrow =4, ncol = 5) 
# 인자에 byrow = T 추가한다면 행 위주로 데이터를 추가 디폴트 값은 컬럼 위주로 데이터 추가 
z
z1 <- matrix(1:20,nrow = 4, ncol = 5, byrow = T)
z1

[,1] [,2] [,3] [,4] [,5]
[1,] 1    5     9   13   17  
[2,] 2    6    10   14   18  
[3,] 3    7    11   15   19  
[4,] 4    8    12   16   20

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20

In [5]:
# 기존의 vector또는 matrix를 결합해 새로운 행렬을 만들 수도 있다.
x <- 1:4
y <- 5:8
m1 <- cbind(x,y)
m2 <- rbind(x,y)
m1
m2
m3 <- rbind(m2,x)
m4 <- cbind(z,x)
m3
m4

x y
[1,] 1 5
[2,] 2 6
[3,] 3 7
[4,] 4 8

[,1] [,2] [,3] [,4]
x 1    2    3    4   
y 5    6    7    8

[,1] [,2] [,3] [,4]
x 1    2    3    4   
y 5    6    7    8   
x 1    2    3    4

x
[1,] 1 5  9 13 17 1
[2,] 2 6 10 14 18 2
[3,] 3 7 11 15 19 3
[4,] 4 8 12 16 20 4

In [6]:
# matrix 안에서의 위치지정
z[2,3]
z[1,4]
z[2,]
z[,4]

[1] 10

[1] 13

[1]  2  6 10 14 18

[1] 13 14 15 16

In [7]:
rownames(z)
colnames(z)
rownames(z) <- c("row1","row2","row3","row4")
colnames(z) <- c("col1","col2","col3","col4","col5")
z

NULL

NULL

col1 col2 col3 col4 col5
row1 1    5     9   13   17  
row2 2    6    10   14   18  
row3 3    7    11   15   19  
row4 4    8    12   16   20

In [ ]:
# [연습1]

In [18]:
# 다음과 같은 내용의 matrix를 생성하시오
m <- c(10,40,60,20)
f <- c(21,60,70,30)
score <- cbind(m,f)
score
# 컬럼의 이름을 각각 male,female로 바꾸시오
colnames(score) <- c("male","female")
score
# 2행에 있는 모든 값을 보이시오 
score[,2]
# female의 모든 값을 보이시오
score[,'female']
# 3행 2열의 값을 보이시오
score[3,2]

m  f 
[1,] 10 21
[2,] 40 60
[3,] 60 70
[4,] 20 30

male female
[1,] 10   21    
[2,] 40   60    
[3,] 60   70    
[4,] 20   30

[1] 21 60 70 30

[1] 21 60 70 30

female 
    70

In [ ]:
# 2. Data Frame

In [9]:
# data frame 만들기
city <- c("Seoul","Tokyo","washington")
rank <- c(1,3,2)
city.info  <- data.frame(city, rank)

city.info[1,]
city.info[2,]
city.info[3,]
city.info

city  rank
1 Seoul 1

city  rank
2 Tokyo 3

city       rank
3 washington 2

city       rank
1 Seoul      1   
2 Tokyo      3   
3 washington 2

In [5]:
# data.frame인 경우 열(Column)별 데이터를 뽑는 것이 가능하다. (matrix에서는 불가능)
# data.frame의 경우 컬럼별로 데이터를 뽑을 경우 그 결과가 data.frame으로 출력
# 그러나 matrix는 vactor형식으로 출력

head(iris) 
is.data.frame(iris)
head(iris[,"Species"]) # 벡터로 출력
head(iris['Species']) # 데이터 프레임으로 출력
head(iris$Species) # 벡터로 출력

Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1 5.1          3.5         1.4          0.2         setosa 
2 4.9          3.0         1.4          0.2         setosa 
3 4.7          3.2         1.3          0.2         setosa 
4 4.6          3.1         1.5          0.2         setosa 
5 5.0          3.6         1.4          0.2         setosa 
6 5.4          3.9         1.7          0.4         setosa

[1] TRUE

[1] setosa setosa setosa setosa setosa setosa
Levels: setosa versicolor virginica

Species
1 setosa 
2 setosa 
3 setosa 
4 setosa 
5 setosa 
6 setosa

[1] setosa setosa setosa setosa setosa setosa
Levels: setosa versicolor virginica

In [19]:
# 선택적으로 데이터를 확인
head(iris[,c(1:2)])
head(iris[,c(1,3,5)])
head(iris[1:50,])
head(iris[1:50,c(1:3)])

Sepal.Length Sepal.Width
1 5.1          3.5        
2 4.9          3.0        
3 4.7          3.2        
4 4.6          3.1        
5 5.0          3.6        
6 5.4          3.9

Sepal.Length Petal.Length Species
1 5.1          1.4          setosa 
2 4.9          1.4          setosa 
3 4.7          1.3          setosa 
4 4.6          1.5          setosa 
5 5.0          1.4          setosa 
6 5.4          1.7          setosa

Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1 5.1          3.5         1.4          0.2         setosa 
2 4.9          3.0         1.4          0.2         setosa 
3 4.7          3.2         1.3          0.2         setosa 
4 4.6          3.1         1.5          0.2         setosa 
5 5.0          3.6         1.4          0.2         setosa 
6 5.4          3.9         1.7          0.4         setosa

Sepal.Length Sepal.Width Petal.Length
1 5.1          3.5         1.4         
2 4.9          3.0         1.4         
3 4.7          3.2         1.3         
4 4.6          3.1         1.5         
5 5.0          3.6         1.4         
6 5.4          3.9         1.7

In [ ]:
# matrix, data.frame 다루기

In [ ]:
str(iris) #데이터 셋 요약 보기
unique(iris[,5]) # 종의 종류 보기 (중복제거)
table(iris[,"Specie"]) #품종의 종류별 instance count

In [22]:
colSums(iris[,-5]) # 열별 합계
colMeans(iris[,-5]) # 열별 평균
head(rowSums(iris[,-5])) # 행별 합계
head(rowMeans(iris[,-5])) # 행별 평균

Sepal.Length  Sepal.Width Petal.Length  Petal.Width 
       876.5        458.6        563.7        179.9

Sepal.Length  Sepal.Width Petal.Length  Petal.Width 
    5.843333     3.057333     3.758000     1.199333

[1] 10.2  9.5  9.4  9.4 10.2 11.4

[1] 2.550 2.375 2.350 2.350 2.550 2.850

In [23]:
# 행과 열 변환하기(transpose)하기 
z <- matrix(1:20,nrow =4, ncol=5)
z
t(z)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    5     9   13   17  
[2,] 2    6    10   14   18  
[3,] 3    7    11   15   19  
[4,] 4    8    12   16   20

[,1] [,2] [,3] [,4]
[1,]  1    2    3    4  
[2,]  5    6    7    8  
[3,]  9   10   11   12  
[4,] 13   14   15   16  
[5,] 17   18   19   20

In [25]:
# subset: 조건에 맞는 행(row) 추출
# subset은 matrix에서 잘 안됨

IR.1 <- subset(iris,Species == "setosa")
head(IR.1)
IR.2 <- subset(iris, Sepal.Length> 5.0 &
              Sepal.Width> 4.0)
IR.2

Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1 5.1          3.5         1.4          0.2         setosa 
2 4.9          3.0         1.4          0.2         setosa 
3 4.7          3.2         1.3          0.2         setosa 
4 4.6          3.1         1.5          0.2         setosa 
5 5.0          3.6         1.4          0.2         setosa 
6 5.4          3.9         1.7          0.4         setosa

Sepal.Length Sepal.Width Petal.Length Petal.Width Species
16 5.7          4.4         1.5          0.4         setosa 
33 5.2          4.1         1.5          0.1         setosa 
34 5.5          4.2         1.4          0.2         setosa

In [26]:
# matrix 간에도 사칙연산 가능(행/열의 수가 동일할 때)
# 수학시간에 배우는 행렬의 곱과는 다르고 단순히 대응하는 위치에 있는 수치들끼리 사칙연산 수행
a <- matrix(1:20,4,5)
b <- matrix(21:40,4,5)
a
b
a+b
b-a
b/a
a*b

[,1] [,2] [,3] [,4] [,5]
[1,] 1    5     9   13   17  
[2,] 2    6    10   14   18  
[3,] 3    7    11   15   19  
[4,] 4    8    12   16   20

[,1] [,2] [,3] [,4] [,5]
[1,] 21   25   29   33   37  
[2,] 22   26   30   34   38  
[3,] 23   27   31   35   39  
[4,] 24   28   32   36   40

[,1] [,2] [,3] [,4] [,5]
[1,] 22   30   38   46   54  
[2,] 24   32   40   48   56  
[3,] 26   34   42   50   58  
[4,] 28   36   44   52   60

[,1] [,2] [,3] [,4] [,5]
[1,] 20   20   20   20   20  
[2,] 20   20   20   20   20  
[3,] 20   20   20   20   20  
[4,] 20   20   20   20   20

[,1]      [,2]     [,3]     [,4]     [,5]    
[1,] 21.000000 5.000000 3.222222 2.538462 2.176471
[2,] 11.000000 4.333333 3.000000 2.428571 2.111111
[3,]  7.666667 3.857143 2.818182 2.333333 2.052632
[4,]  6.000000 3.500000 2.666667 2.250000 2.000000

[,1] [,2] [,3] [,4] [,5]
[1,] 21   125  261  429  629 
[2,] 44   156  300  476  684 
[3,] 69   189  341  525  741 
[4,] 96   224  384  576  800

In [27]:
# matrix와 Data Frame은 외관상 비슷 
# 자료 구조를 확인하기 위해 class함수를 사용 
class(iris)
class(state.x77)

[1] "data.frame"

[1] "matrix"

In [28]:
# dataframe을 matrix형태로 변환
iris.m <- as.matrix(iris[,1:4])
head(iris.m)
class(iris.m)

Sepal.Length Sepal.Width Petal.Length Petal.Width
[1,] 5.1          3.5         1.4          0.2        
[2,] 4.9          3.0         1.4          0.2        
[3,] 4.7          3.2         1.3          0.2        
[4,] 4.6          3.1         1.5          0.2        
[5,] 5.0          3.6         1.4          0.2        
[6,] 5.4          3.9         1.7          0.4

[1] "matrix"

In [ ]:
# 4. 파일에 데이터 읽기/쓰기

In [ ]:
# 파일에서 데이터 읽어보기 
# csv 포멧으로 저장
# read.csv()함수 이용 
# 디렉토리 구분자는 \가 아닌 /를 사용 

In [30]:
getwd()
setwd("D:/py_fi/1._R기초교육/Rworks")
getwd()
mydata <- read.csv("test.csv",header = TRUE) # 첫줄이 컬럼이 아닌 데이터일 경우 header = False로 인자 변경 TRUE는 디폴트값
head(mydata)

[1] "D:/py_fi/1._R기초교육/Rworks"

[1] "D:/py_fi/1._R기초교육/Rworks"

SL  SW  PL  PW  Group 
1 5.1 3.5 1.4 0.2 setosa
2 4.9 3.0 1.4 0.2 setosa
3 4.7 3.2 1.3 0.2 setosa
4 4.6 3.1 1.5 0.2 setosa
5 5.0 3.6 1.4 0.2 setosa
6 5.4 3.9 1.7 0.4 setosa

In [ ]:
# 5. List와 Factor

In [32]:
# List
# 벡터와 비슷하나 벡터와 달리 여러 자료형의 데이터를 섞어서 저장할 수 있다. (vactor나 data frame등도 원소로 저장 가능)

member <- list(name = 'kim',address = 'busan',boolean = TRUE)
member

# list에서 요소값을 불러올때는 [[]]
member[[1]]
member$name

$name
[1] "kim"

$address
[1] "busan"

$boolean
[1] TRUE

[1] "kim"

[1] "kim"

In [35]:
# factor 
# 문자형 변수로서 특정 종류의 값만 가질 수 있는 데이터 타입 
# 혈액형과 같이 종류에 대한 데이터 타입에 사용한다. 
blood_type <- factor(c("A","A","AB","O","B"))
print(blood_type)
is.factor(blood_type)
blood_type[6] <- "D" # 오류 발생

[1] A  A  AB O  B 
Levels: A AB B O


[1] TRUE

Warning message in `[<-.factor`(`*tmp*`, 6, value = "D"):
"invalid factor level, NA generated"

In [36]:
# Factor는 Label 순서대로 숫자로 변환할 수 있다. 
blood_type
as.numeric(blood_type)


[1] A    A    AB   O    B    <NA>
Levels: A AB B O

[1]  1  1  2  4  3 NA

[1] A    A    AB   O    B    <NA>
Levels: A AB B O
